/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : phonenumber
 #	author : miyako
 #	2017/07/08
 #
 # --------------------------------------------------------------------------------*/

#include "phonenumbers/phonenumber.h"
#include "phonenumbers/phonenumberutil.h"
#include "phonenumbers/geocoding/phonenumber_offline_geocoder.h"

#include "libjson/libjson.h"
#include "libjson_methods.h"

#include <mutex>

// --- Phone Number
void Parse_phone_number(sLONG_PTR *pResult, PackagePtr pParams);
